[2025-01-11T13:36:55.245+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-11T13:36:55.298+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dynamic_task_mapping_with_fixed_chunk_size_operator.process_chunk manual__2025-01-11T13:36:50.165747+00:00 map_index=2 [queued]>
[2025-01-11T13:36:55.319+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dynamic_task_mapping_with_fixed_chunk_size_operator.process_chunk manual__2025-01-11T13:36:50.165747+00:00 map_index=2 [queued]>
[2025-01-11T13:36:55.320+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-11T13:36:55.402+0000] {taskinstance.py:2889} INFO - Executing <Mapped(PythonOperator): process_chunk> on 2025-01-11 13:36:50.165747+00:00
[2025-01-11T13:36:55.428+0000] {standard_task_runner.py:72} INFO - Started process 1454 to run task
[2025-01-11T13:36:55.448+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dynamic_task_mapping_with_fixed_chunk_size_operator', 'process_chunk', 'manual__2025-01-11T13:36:50.165747+00:00', '--job-id', '845', '--raw', '--subdir', 'DAGS_FOLDER/experiments/dynamic_task_mapping_sequentials.py', '--cfg-path', '/tmp/tmp1apmr3xh', '--map-index', '2']
[2025-01-11T13:36:55.460+0000] {standard_task_runner.py:105} INFO - Job 845: Subtask process_chunk
[2025-01-11T13:36:55.965+0000] {task_command.py:467} INFO - Running <TaskInstance: dynamic_task_mapping_with_fixed_chunk_size_operator.process_chunk manual__2025-01-11T13:36:50.165747+00:00 map_index=2 [running]> on host 02aab7e5da88
[2025-01-11T13:36:56.830+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3115, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3534, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/mappedoperator.py", line 912, in render_template_fields
    mapped_kwargs, seen_oids = self._expand_mapped_kwargs(context, session, include_xcom=True)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/mappedoperator.py", line 700, in _expand_mapped_kwargs
    return self._get_specified_expand_input().resolve(context, session, include_xcom=include_xcom)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/expandinput.py", line 281, in resolve
    raise ValueError(f"expand_kwargs() expects a list[dict], not list[{_describe_type(mapping)}]")
ValueError: expand_kwargs() expects a list[dict], not list[list]
[2025-01-11T13:36:57.267+0000] {taskinstance.py:3359} ERROR - Unable to unmap task to determine if we need to send an alert email
[2025-01-11T13:36:57.276+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dynamic_task_mapping_with_fixed_chunk_size_operator, task_id=process_chunk, run_id=manual__2025-01-11T13:36:50.165747+00:00, map_index=2, execution_date=20250111T133650, start_date=20250111T133655, end_date=20250111T133656
[2025-01-11T13:36:57.354+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-11T13:36:57.361+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 845 for task process_chunk (expand_kwargs() expects a list[dict], not list[list]; 1454)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3115, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3534, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/mappedoperator.py", line 912, in render_template_fields
    mapped_kwargs, seen_oids = self._expand_mapped_kwargs(context, session, include_xcom=True)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/mappedoperator.py", line 700, in _expand_mapped_kwargs
    return self._get_specified_expand_input().resolve(context, session, include_xcom=include_xcom)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/expandinput.py", line 281, in resolve
    raise ValueError(f"expand_kwargs() expects a list[dict], not list[{_describe_type(mapping)}]")
ValueError: expand_kwargs() expects a list[dict], not list[list]
[2025-01-11T13:36:57.432+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-11T13:36:57.677+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-11T13:36:57.681+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
