[2025-01-11T13:47:20.031+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-11T13:47:20.078+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dynamic_task_mapping_python_operator.process_chunk manual__2025-01-11T13:47:14.901912+00:00 map_index=5 [queued]>
[2025-01-11T13:47:20.092+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dynamic_task_mapping_python_operator.process_chunk manual__2025-01-11T13:47:14.901912+00:00 map_index=5 [queued]>
[2025-01-11T13:47:20.094+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-11T13:47:20.124+0000] {taskinstance.py:2889} INFO - Executing <Mapped(PythonOperator): process_chunk> on 2025-01-11 13:47:14.901912+00:00
[2025-01-11T13:47:20.130+0000] {standard_task_runner.py:72} INFO - Started process 1636 to run task
[2025-01-11T13:47:20.136+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dynamic_task_mapping_python_operator', 'process_chunk', 'manual__2025-01-11T13:47:14.901912+00:00', '--job-id', '859', '--raw', '--subdir', 'DAGS_FOLDER/experiments/dynamic_task_mapping_sequentials.py', '--cfg-path', '/tmp/tmps492i_1a', '--map-index', '5']
[2025-01-11T13:47:20.141+0000] {standard_task_runner.py:105} INFO - Job 859: Subtask process_chunk
[2025-01-11T13:47:20.302+0000] {task_command.py:467} INFO - Running <TaskInstance: dynamic_task_mapping_python_operator.process_chunk manual__2025-01-11T13:47:14.901912+00:00 map_index=5 [running]> on host 02aab7e5da88
[2025-01-11T13:47:21.345+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dynamic_task_mapping_python_operator' AIRFLOW_CTX_TASK_ID='process_chunk' AIRFLOW_CTX_EXECUTION_DATE='2025-01-11T13:47:14.901912+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-11T13:47:14.901912+00:00'
[2025-01-11T13:47:21.355+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-11T13:47:21.404+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
TypeError: process_chunk() takes 1 positional argument but 51000 were given
[2025-01-11T13:47:21.442+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dynamic_task_mapping_python_operator, task_id=process_chunk, run_id=manual__2025-01-11T13:47:14.901912+00:00, map_index=5, execution_date=20250111T134714, start_date=20250111T134720, end_date=20250111T134721
[2025-01-11T13:47:21.567+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-11T13:47:21.663+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 859 for task process_chunk (process_chunk() takes 1 positional argument but 51000 were given; 1636)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
TypeError: process_chunk() takes 1 positional argument but 51000 were given
[2025-01-11T13:47:21.896+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-11T13:47:22.042+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-11T13:47:22.049+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
