[2025-01-11T12:43:51.853+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-11T12:43:51.862+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dynamic_task_mapping_with_fixed_chunk_size.generate_task manual__2025-01-11T12:43:50.155507+00:00 map_index=0 [queued]>
[2025-01-11T12:43:51.868+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dynamic_task_mapping_with_fixed_chunk_size.generate_task manual__2025-01-11T12:43:50.155507+00:00 map_index=0 [queued]>
[2025-01-11T12:43:51.868+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-11T12:43:51.873+0000] {taskinstance.py:2889} INFO - Executing <Mapped(PythonOperator): generate_task> on 2025-01-11 12:43:50.155507+00:00
[2025-01-11T12:43:51.876+0000] {standard_task_runner.py:72} INFO - Started process 580 to run task
[2025-01-11T12:43:51.879+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dynamic_task_mapping_with_fixed_chunk_size', 'generate_task', 'manual__2025-01-11T12:43:50.155507+00:00', '--job-id', '786', '--raw', '--subdir', 'DAGS_FOLDER/experiments/dynamic_task_mapping_sequentials_dag.py', '--cfg-path', '/tmp/tmpg7m59feg', '--map-index', '0']
[2025-01-11T12:43:51.880+0000] {standard_task_runner.py:105} INFO - Job 786: Subtask generate_task
[2025-01-11T12:43:51.903+0000] {task_command.py:467} INFO - Running <TaskInstance: dynamic_task_mapping_with_fixed_chunk_size.generate_task manual__2025-01-11T12:43:50.155507+00:00 map_index=0 [running]> on host 02aab7e5da88
[2025-01-11T12:43:52.183+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dynamic_task_mapping_with_fixed_chunk_size' AIRFLOW_CTX_TASK_ID='generate_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-11T12:43:50.155507+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-11T12:43:50.155507+00:00'
[2025-01-11T12:43:52.186+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-11T12:43:52.216+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 234, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/context.py", line 421, in context_merge
    context.update(*args, **kwargs)
  File "/usr/local/lib/python3.10/_collections_abc.py", line 1004, in update
    for key, value in other:
ValueError: too many values to unpack (expected 2)
[2025-01-11T12:43:52.266+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dynamic_task_mapping_with_fixed_chunk_size, task_id=generate_task, run_id=manual__2025-01-11T12:43:50.155507+00:00, map_index=0, execution_date=20250111T124350, start_date=20250111T124351, end_date=20250111T124352
[2025-01-11T12:43:52.311+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-11T12:43:52.313+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 786 for task generate_task (too many values to unpack (expected 2); 580)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 234, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/context.py", line 421, in context_merge
    context.update(*args, **kwargs)
  File "/usr/local/lib/python3.10/_collections_abc.py", line 1004, in update
    for key, value in other:
ValueError: too many values to unpack (expected 2)
[2025-01-11T12:43:52.361+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-11T12:43:52.392+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-11T12:43:52.394+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
